#
# Enable the multiqueue schedulers in Ubuntu 18.04 - requires reboot for effect.
#
---
- hosts: '{{ playhosts | default("cpu-worker-node") }}'
  gather_facts: false
  roles:
    - { role: ais_enable_multiqueue }
  tasks:


- hosts: all
  gather_facts: false
  tasks:

    - name: Reboot Server
      reboot:
        reboot_timeout: 3600
